Rails/tacta/config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  root 'contacts#index'

end

Rails/tacta/app/models/contact.rb
class Contact < ActiveRecord::Base

   validates :name, presence: true
   validates :name, uniqueness: true

   validates :phone, allow_blank: true, length: { in: 5..20 }
   validates :email, allow_blank: true, length: { in: 5..50 }

   validates_format_of :phone, allow_blank: true, :with => /\A[+ 0-9]+$\z/
   validates_format_of :email, allow_blank: true, :with => /@/, message: 'must contain @.'
s
end

Rails/tacta/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/tacta/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
      @contacts = Contact.all
   end

   def show
     @contact = Contact.find( params[:id] )
  end

  def new
      @contact = Contact.new
   end

   def create
       contact_params

       @contact = Contact.new( contact_params )

       if @contact.save
          redirect_to @contact
       else
          render 'new'
       end
     end

     def update
       @contact = Contact.find( params[:id] )

       contact_params

       if @contact.update_attributes( contact_params )
          redirect_to @contact
       else
          render 'edit'
       end
     end

     def destroy
      @contact = Contact.find( params[:id] )

      @contact.destroy

      redirect_to contacts_path
   end

     private

   def contact_params
      params.require( :contact ).permit( :name, :phone, :email )
   end

end

Rails/tacta/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/tacta/app/helpers/contacts_helper.rb
module ContactsHelper
end

Rails/tacta/app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
    </ul>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :phone %>
    <%= f.text_field :phone, size: 15 %>

    <%= f.label :email %>
    <%= f.text_field :email, size: 20 %>

    <%= f.submit (@contact.new_record? ? "Create" : "Update") %>

<% end %>

Rails/tacta/app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render "form" %>

Rails/tacta/app/views/contacts/index.html.erb
<h1>Contacts</h1>

<% @contacts.each do |contact| %>
    <p><%= link_to contact.name, contact_path( contact.id ) %></p>
<% end %>

<%= link_to "[New Contact]", new_contact_path %>

Rails/tacta/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render "form" %>

Rails/tacta/app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p>Phone: <%= @contact.phone %></p>
<p>Email: <%= @contact.email %></p>

<%= link_to "[Edit]", edit_contact_path( @contact.id ) %>
<%= link_to "[Delete]", contact_path( @contact.id ), method: :delete, data: { confirm: "Are you sure?" } %>

Rails/tacta/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tacta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<br><br>
<hr>

<%= link_to "[All Contacts]", root_path %>

</body>
</html>